services:
  inventario_web:
    build: .
    image: sistemadegestion-web
    container_name: inventario_web
    restart: always
    env_file:
      - .env
    environment:
      VIRTUAL_HOST: www.mwtanquesinventario.com
      LETSENCRYPT_HOST: www.mwtanquesinventario.com
      LETSENCRYPT_EMAIL: tu_email@dominio.com
      VIRTUAL_PORT: 5000
    expose:
      - "5000"
    depends_on:
      - inventario_db
    networks:
      - inventario_net

  inventario_db:
    image: postgres:15
    container_name: inventario_db
    restart: always
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - inventario_net

  inventario_nginx_proxy:
    image: jwilder/nginx-proxy
    container_name: inventario_nginx_proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - nginx_certs:/etc/nginx/certs
      - nginx_vhost:/etc/nginx/vhost.d
      - nginx_html:/usr/share/nginx/html
    networks:
      - inventario_net

  inventario_letsencrypt:
    image: nginxproxy/acme-companion
    container_name: inventario_letsencrypt
    restart: always
    environment:
      NGINX_PROXY_CONTAINER: inventario_nginx_proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - nginx_certs:/etc/nginx/certs
      - nginx_vhost:/etc/nginx/vhost.d
      - nginx_html:/usr/share/nginx/html
      - acme:/etc/acme.sh
    depends_on:
      - inventario_nginx_proxy
    networks:
      - inventario_net

volumes:
  pgdata:
  nginx_certs:
  nginx_vhost:
  nginx_html:
  acme:

networks:
  inventario_net:
    driver: bridge
